### ISSUE TITLE
添加.env文件后flask命令无法使用了

### ISSUE THREAD

**Issue by driftalong2** [weijiang1994/Blogin#22]
我在使用`flask initdb`的时候发现了下面的错误，经过查找，发现添加.env文件后flask命令无法使用了，就会报这个错误，请问能怎么解决吗？

> (python38) D:\DATA\resume\Blogin-master>flask initdb
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\ProgramData\Anaconda3\envs\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\ProgramData\Anaconda3\envs\python38\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\flask\cli.py", line 575, in main
    load_dotenv()
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\flask\cli.py", line 649, in load_dotenv
    dotenv.load_dotenv(path)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\dotenv\main.py", line 312, in load_dotenv
    return DotEnv(f, verbose=verbose, interpolate=interpolate, **kwargs).set_as_environment_variables(override=override)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\dotenv\main.py", line 102, in set_as_environment_variables
    for k, v in self.dict().items():
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\dotenv\main.py", line 86, in dict
    values = OrderedDict(self.parse())
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\dotenv\main.py", line 93, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\dotenv\main.py", line 48, in with_warn_for_invalid_lines
    for mapping in mappings:
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\dotenv\parser.py", line 235, in parse_stream
    reader = Reader(stream)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\dotenv\parser.py", line 107, in __init__
    self.string = stream.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 113: illegal multibyte sequence

**Comment by weijiang1994** [comment]
把`.env`文件中的中文注释去掉，应该就可以了~方便的话帮忙点个star吧 谢谢啦 :smile:

**Comment by driftalong2** [comment]
我之前还用notepad++改了UFT-8编码，没想到是这个。

**Comment by driftalong2** [comment]
我又遇到了另外一个错误，为什么网站里还用了百度OCR呢？

> (python38) D:\DATA\resume\Blogin-master>flask initdb
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\ProgramData\Anaconda3\envs\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\ProgramData\Anaconda3\envs\python38\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\click\core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\click\core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\flask\cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\flask\cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "D:\DATA\resume\Blogin-master\wsgi.py", line 8, in <module>
    from blogin import create_app
  File "D:\DATA\resume\Blogin-master\blogin\__init__.py", line 19, in <module>
    from blogin.blueprint.front.blog import blog_bp
  File "D:\DATA\resume\Blogin-master\blogin\blueprint\front\blog.py", line 16, in <module>
    from blogin.utils import redirect_back, github_social, BOOTSTRAP_SUFFIX
  File "D:\DATA\resume\Blogin-master\blogin\utils.py", line 282, in <module>
    OCR_TOKEN = config_ini.get('baidu', 'token')
  File "E:\ProgramData\Anaconda3\envs\python38\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'baidu'

在utils.py是这样的：

> # 百度OCR配置
OCR_URL = 'https://aip.baidubce.com/rest/2.0/ocr/v1/'
OCR_TOKEN = config_ini.get('baidu', 'token')
OCR_HEADERS = {'content-type': 'application/x-www-form-urlencoded'}

>

**Comment by weijiang1994** [comment]
都可以，这个OCR是我图片转换文字的一个工具，你在`res`目录下新建`config.ini`文件然后把下面的内容输入进去就行
```ini
[baidu]
ak = example-baidu-ak
sk = example-baidu-sk
token = example-baidu-token

[base]
scheduler = True
light_theme = flatly
dark_theme = darkly

[admin]
author_email = example@mail.com
gallery_slogan = sample text
```

**Comment by driftalong2** [comment]
请问网站的管理逻辑是怎么样的呢？我在网站https://2dogz.cn里也没有找到教程。

现在我用超级管理员登入了网站，但是没有显示admin权限的地方，然后我直接输入http://127.0.0.1:5000/admin/blog，404。

我能加你微信向您请教吗？`junny_alone`

**Comment by weijiang1994** [comment]
我微信 jw804022023
