### ISSUE TITLE
初始化数据库命令失败

### ISSUE THREAD

**Issue by zw1765** [weijiang1994/Blogin#44]
(venv) (base) zw@DESKTOP-TIVUPRV:~/code/Blogin$ flask initdb
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'initdb'.

**Comment by zw1765** [comment]
我已经安装了python-dotenv
pip show python-dotenv
Name: python-dotenv
Version: 0.14.0

**Comment by weijiang1994** [comment]
输入flask --help看看输出啥

**Comment by zw1765** [comment]
File "/home/zw/Downloads/yes/lib/python3.10/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/zw/code/Blogin/blogin/__init__.py", line 32, in <module>
    from blogin.blueprint.front.rss import rss_bp
  File "/home/zw/code/Blogin/blogin/blueprint/front/rss.py", line 9, in <module>
    from feedgen.feed import FeedGenerator
  File "/home/zw/Downloads/yes/lib/python3.10/site-packages/feedgen/feed.py", line 17, in <module>
    from lxml import etree  # nosec - not using this for parsing
ImportError: /home/zw/Downloads/yes/lib/python3.10/site-packages/lxml/etree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zw/Downloads/yes/lib/python3.10/site-packages/flask/cli.py", line 556, in list_commands
    rv.update(info.load_app().cli.list_commands(ctx))
  File "/home/zw/Downloads/yes/lib/python3.10/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/zw/Downloads/yes/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing "blogin", an ImportError was raised:

Traceback (most recent call last):
  File "/home/zw/Downloads/yes/lib/python3.10/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/zw/code/Blogin/blogin/__init__.py", line 32, in <module>
    from blogin.blueprint.front.rss import rss_bp
  File "/home/zw/code/Blogin/blogin/blueprint/front/rss.py", line 9, in <module>
    from feedgen.feed import FeedGenerator
  File "/home/zw/Downloads/yes/lib/python3.10/site-packages/feedgen/feed.py", line 17, in <module>
    from lxml import etree  # nosec - not using this for parsing
ImportError: /home/zw/Downloads/yes/lib/python3.10/site-packages/lxml/etree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send

Usage: flask [OPTIONS] COMMAND [ARGS]...

  A general utility script for Flask applications.

  Provides commands from Flask, extensions, and the application. Loads the
  application defined in the FLASK_APP environment variable, or from a
  wsgi.py file. Setting the FLASK_ENV environment variable to 'development'
  will enable debug mode.

    $ export FLASK_APP=hello.py
    $ export FLASK_ENV=development
    $ flask run

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  db      Perform database migrations.
  routes  Show the routes for the app.
  run     Run a development server.
  shell   Run a shell in the app context.

**Comment by weijiang1994** [comment]
ImportError: /home/zw/Downloads/yes/lib/python3.10/site-packages/lxml/etree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
这里有问题

**Comment by weijiang1994** [comment]
你升级一下feedgen这个的版本试试

**Comment by zw1765** [comment]
上面的问题解决了，是我的python版本过高的问题。
现在我完成了上面的步骤，出现了登录界面打不开

**Comment by zw1765** [comment]
* Detected change in '/home/zw/code/Blogin/blogin/models.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 218-395-850
127.0.0.1 - - [18/Oct/2023 14:39:31] "GET /auth/login/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zw/code/Blogin/blogin/blueprint/front/auth.py", line 53, in login
    ban_ip = rd.get(str(remote_ip))
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/zw/code/Blogin/venv/lib/python3.8/site-packages/redis/connection.py", line 340, in read_response
    raise error
redis.exceptions.AuthenticationError: Authentication required.
127.0.0.1 - - [18/Oct/2023 14:39:32] "GET /auth/login/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2023 14:39:32] "GET /auth/login/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2023 14:39:32] "GET /auth/login/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2023 14:39:32] "GET /auth/login/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2023 14:39:32] "GET /auth/login/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2023 14:39:32] "GET /auth/login/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by weijiang1994** [comment]
redis配置不对

**Comment by zw1765** [comment]
需要在哪里设置redis账号密码呢

**Comment by weijiang1994** [comment]
你看ban_ip = rd.get(str(remote_ip))这句代码的rd在哪里定义的，就在那里配置。

**Comment by zw1765** [comment]
后台管理，怎么打开呀。我登录了管理员用户，找不到新建博客等内容

**Comment by jingk-1992** [comment]
老铁找到了吗，我也没找到
